import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import {NextIntlClientProvider} from 'next-intl';

const cairo = Cairo({
  subsets: ["arabic"],
  weight:[ "200", "400",],
  display: 'swap',
  variable: "--font-cairo", 
});


export const metadata: Metadata = {
  title: "bilkhidmah",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="">
      <body
      style={{ fontFamily:'Cairo'}}
        className={` ${cairo.variable} antialiased`}
      >
           <NextIntlClientProvider>
           {children}
           </NextIntlClientProvider>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js" />
 <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js" />
      </body>
    </html>
  );
}
